import React, { createContext, useContext, useState, useEffect } from "react";

const LanguageContext = createContext();

export const translations = {
  en: {
    // Navbar
    nav: {
      home: "Home",
      about: "About",
      experience: "Experience",
      projects: "Projects",
      skills: "Skills",
      certificates: "Certificates",
      contact: "Contact",
      resume: "Resume / CV",
      portfolio: "PORTFOLIO",
    },
    // Hero
    hero: {
      status: "Open for Opportunities",
      academic: "🎓 S1 Telecommunications Engineering",
      greeting: "Hi, I'm",
      specialization: "Computer Vision • IoT Development • Front-End Engineering",
      bio1: "Telecommunications Engineering graduate with practical experience in Edge AI, Computer Vision, and industry internships at PT LEN Industri (Persero) and HUMIC Engineering.",
      bio2: "Experienced in deploying YOLOv8 edge models on Raspberry Pi 5, building ESP32 IoT connected devices, creating dynamic Looker Studio dashboards, and developing modern React web applications.",
      viewExperience: "View Experience & Work",
      downloadCV: "Download Formal CV",
      getInTouch: "Get in Touch →",
      stats: {
        internships: { label: "Industry Internships", sub: "PT LEN & HUMIC" },
        projects: { label: "Featured Projects", sub: "Edge AI • IoT • Web • Data" },
        certs: { label: "Certifications", sub: "DeepLearning.AI & Dicoding" },
        specializations: { label: "Specializations", sub: "Computer Vision • IoT • Web" },
      },
    },
    // About
    about: {
      badge: "BACKGROUND & PROFILE",
      title: "About",
      titleSpan: "Me",
      subtitle: "Telecommunications Engineering graduate with an interdisciplinary background across Computer Vision, IoT embedded systems, and Front-End engineering.",
      profileTitle: "Professional Profile",
      story1: "I am a Telecommunications Engineering graduate with a robust technical focus bridging embedded hardware, intelligent edge computer vision models, and modern web/mobile interfaces.",
      story2: "Throughout my academic tenure, I have developed extensive practical expertise through active laboratory assistantship at MBC Laboratory and industry internships at PT LEN Industri (Persero) and HUMIC Engineering.",
      story3: "In my Capstone Design project, I led the end-to-end implementation of an edge computer vision people counting system deploying YOLOv8n and ByteTrack on Raspberry Pi 5 with full Firebase and Flutter mobile app integration.",
      higherEdu: "Higher Education",
      eduDegree: "S1 Telecommunications Engineering",
      eduPeriod: "2022 - 2026",
      eduDesc: "Focused on digital signal processing, embedded systems, network fundamentals, telecommunications systems, and artificial intelligence integration.",
      softSkillsTitle: "Core Work Ethos & Soft Skills",
      softSkills: [
        { name: "Time Management", desc: "Structured deadline execution & sprint tracking" },
        { name: "High Discipline", desc: "Detail-oriented research and code standards" },
        { name: "High Adaptability", desc: "Rapid adoption of emerging tech stacks" },
        { name: "Team Collaboration", desc: "Proven cross-functional lab & team coordination" },
      ],
      pillarsTitle: "Areas of Expertise",
      pillars: [
        {
          title: "Computer Vision & Edge AI",
          description: "YOLOv8 object detection, ByteTrack Multi-Object Tracking, edge deployment on Raspberry Pi 5 & FP16 PyTorch optimization.",
        },
        {
          title: "Internet of Things (IoT)",
          description: "Microcontroller programming (ESP32/Arduino) with sensor integration (Ultrasonic, Tilt, Buzzer) and Blynk.io cloud telemetry.",
        },
        {
          title: "Front-End & Mobile Apps",
          description: "Interactive and responsive web applications with React.js & Tailwind CSS, and mobile monitoring apps with Flutter.",
        },
        {
          title: "PMO & Data Analytics",
          description: "Enterprise project management dashboards, budget oversight, and workflow optimization using Google Looker Studio and AppSheet.",
        },
      ],
    },
    // Experience
    experience: {
      badge: "CAREER & LEADERSHIP TIMELINE",
      title: "Professional",
      titleSpan: "Experience",
      subtitle: "Proven track record in industrial engineering internships, deep learning research, laboratory instruction, and student leadership.",
      tabWork: "💼 Industry Internships",
      tabOrg: "🏛️ Lab Assistant & Organizations",
      workList: [
        {
          role: "Deep Learning Engineer, Internship",
          company: "HUMIC (Human Centric) Engineering",
          location: "Bandung, Indonesia",
          period: "Apr 2026 - Jul 2026",
          type: "Industrial Research Internship",
          highlights: [
            "Designed and implemented PyTorch Deep Learning architectures (Multi-Branch 1D/2D CNN & BiLSTM-MHA) for speech-based depression detection using the DAIC-WOZ dataset (189 participants) under strict participant-level 5-Fold Stratified Cross-Validation.",
            "Integrated self-supervised pre-trained representations (Wav2Vec 2.0 768-dim embeddings) with Mel-Spectrograms and 120-dim MFCCs into a multi-modal deep feature fusion head.",
            "Mitigated severe class imbalance (2.3:1 ratio) through custom AdamW optimization, ReduceLROnPlateau scheduling, 0.4 dropout regularization, and weighted Cross-Entropy Loss penalties.",
            "Engineered Explainable AI (XAI) attribution pipelines leveraging SHAP GradientExplainer directly on CNN fusion layers to interpret spectral-temporal audio feature attributions for clinical transparency.",
          ],
          tags: ["PyTorch", "Wav2Vec 2.0", "BiLSTM-MHA", "SHAP XAI", "Audio Processing"],
        },
        {
          role: "Project Management Officer, Internship",
          company: "PT LEN Industri (Persero)",
          location: "Bandung, Indonesia",
          period: "Jun 2025 - Sept 2025",
          type: "State-Owned Enterprise (BUMN) Internship",
          highlights: [
            "Developed and managed project dashboards using Google Looker Studio for dynamic, real-time project monitoring with a primary focus on budget oversight and resource allocation.",
            "Utilized AppSheet and Google Looker to automate and optimize project management processes across the internship period.",
            "Prepared and structured various project management documents required for executive leadership reporting.",
          ],
          tags: ["Google Looker Studio", "AppSheet", "Project Management", "Budget Oversight", "Process Optimization"],
        },
      ],
      orgList: [
        {
          role: "Practicum Division (Laboratory Instructor)",
          company: "MBC LABORATORY",
          location: "Faculty of Electrical Engineering",
          period: "2025 - 2026",
          type: "Academic Laboratory Assistantship",
          highlights: [
            "Taught practical technical engineering material directly to university students to ensure in-depth hands-on understanding.",
            "Compiled and developed practical course modules serving as the primary technical guide in the student learning process.",
            "Installed and configured essential technical software environments to ensure seamless lab practicum execution.",
            "Managed physical lab infrastructure, including workbench layouts and cable management for a safe and conducive environment.",
          ],
          tags: ["Teaching & Mentoring", "Module Development", "System Setup", "Lab Management"],
        },
        {
          role: "Public Relations Division",
          company: "TELERIUM",
          location: "Faculty of Electrical Engineering",
          period: "2023 - 2024",
          type: "Departmental Organization",
          highlights: [
            "Served as the key communication bridge fostering intensive coordination between laboratories across the Faculty of Electrical Engineering.",
            "Ensured smooth information flow between event organizers and laboratory assistants to minimize operational and technical bottlenecks.",
          ],
          tags: ["Cross-Lab Coordination", "Event PR", "Stakeholder Communication"],
        },
        {
          role: "Public Relations Division",
          company: "PERMISI",
          location: "Bekasi",
          period: "2022 - 2023",
          type: "Regional Student Organization",
          highlights: [
            "Actively led outreach in the Education Roadshow project targeting high schools across the Bekasi region.",
            "Conducted intensive direct socialization and built strategic cooperative relationships with high school leaders.",
            "Managed internal team communication, presentation scheduling, and delivered measurable increases in high school outreach participation.",
          ],
          tags: ["Education Outreach", "Public Speaking", "Team Coordination", "Relationship Building"],
        },
      ],
    },
    // Projects
    projects: {
      badge: "TECHNICAL PORTFOLIO",
      title: "Featured",
      titleSpan: "Projects",
      subtitle: "Showcase of engineering projects spanning Computer Vision & Edge AI, IoT systems, web applications, and enterprise dashboards.",
      filters: {
        All: "All Projects",
        AI: "🧠 Computer Vision & AI",
        IoT: "📡 IoT & Hardware",
        Web: "💻 Web Development",
        Data: "📊 Data & PMO",
      },
      viewDetails: "View Details →",
      modalOverview: "Project Overview",
      modalHighlights: "Key Highlights & Architecture",
      modalStack: "Technologies & Stack",
      modalClose: "Close",
      modalLiveDemo: "Launch Live Application ↗",
      modalVideo: "Watch Video Demo (YouTube) ↗",
      modalGitHub: "GitHub Repository",
      list: [
        {
          id: 1,
          title: "Detectra: Edge Computer Vision People Counting",
          subtitle: "Capstone Design Project",
          category: "Computer Vision & Edge AI",
          tagCategory: "AI",
          period: "2026",
          description: "Real-time human monitoring & counting system using YOLOv8n and ByteTrack on Raspberry Pi 5, integrated with dual-path Firebase RTDB and Flutter mobile app.",
          fullDescription: "Undergraduate Capstone Design Project. Engineered an automated edge AI people counting and room occupancy monitoring system deployed on a Raspberry Pi 5 with a Camera Module V2 IMX219, preserving user privacy without facial/biometric identification. Implemented a fine-tuned YOLOv8n model (5,130 custom dataset, 81.41% mAP@0.5, 82.17% precision, ~146 ms inference time / 6.84 FPS) paired with ByteTrack multi-object tracking, virtual line-crossing centroid logic, 2-second anti-oscillation filters, and spawn-side tracking. Built an asynchronous dual-path distribution architecture: streaming numerical data to Firebase Realtime Database and visual snapshots via a local Flask server, monitored via the cross-platform Detectra Flutter mobile app with 90.23% overall system testing accuracy.",
          features: [
            "Edge Object Detection & Tracking (YOLOv8n + ByteTrack Multi-Object Tracking)",
            "Two-Way Virtual Line-Crossing Centroid Counting Logic (IN / OUT)",
            "Anti-Oscillation Cooldown (2s) & Spawn-Side Tracking to Prevent Double Counting",
            "Asynchronous Dual-Path Data Architecture (Firebase Realtime DB + Local Flask Server)",
            "Cross-Platform Detectra Mobile App (Flutter) with Live Status, Analytics, & Remote Control",
            "Overall System Testing Accuracy of 90.23% (Indoor & Outdoor) with 146 ms Inference Latency",
          ],
          badge: "Capstone Project",
        },
        {
          id: 2,
          title: "Speech-Based Depression Detection AI",
          subtitle: "HUMIC Engineering Research Internship",
          category: "AI & Deep Learning",
          tagCategory: "AI",
          period: "Apr 2026 - Jul 2026",
          description: "Designed a multi-branch PyTorch deep learning framework (CNN & BiLSTM-MHA) with Wav2Vec 2.0 feature fusion and Explainable AI (SHAP) for clinical speech depression detection.",
          fullDescription: "A cutting-edge deep learning research project developed at HUMIC (Human Centric) Engineering. Built to detect depression severity from clinical audio interviews (DAIC-WOZ dataset, 189 participants) under strict participant-level 5-Fold Stratified Cross-Validation. Integrated self-supervised Wav2Vec 2.0 (768-dim embeddings) with Mel-Spectrograms and 120-dim MFCCs into a multi-modal feature fusion head. Engineered Explainable AI pipelines via SHAP GradientExplainer to interpret acoustic attributions for clinical transparency.",
          features: [
            "Multi-Branch 1D/2D CNN & BiLSTM-MHA Architecture",
            "Pre-trained Wav2Vec 2.0 768-dim Embeddings Integration",
            "Multi-Modal Deep Feature Fusion with Mel-Spectrograms & MFCCs",
            "Severe Class Imbalance Mitigation (AdamW & Weighted Loss)",
            "Explainable AI (SHAP GradientExplainer) on CNN Fusion Layers",
          ],
          badge: "Deep Learning AI",
        },
        {
          id: 3,
          title: "ESP32 Smart Assistive Device for Visually Impaired",
          subtitle: "IoT Hardware & Cloud Platform Integration",
          category: "IoT & Hardware",
          tagCategory: "IoT",
          period: "Mar 2025 - Jun 2025",
          description: "Engineered an IoT navigation aid for visually impaired individuals using an ESP32 microcontroller, ultrasonic distance sensors, tilt stability sensors, buzzer alarms, and Blynk.io.",
          fullDescription: "Designed and fabricated an assistive smart hardware device aimed at enhancing pedestrian safety and mobility for visually impaired individuals. Powered by an ESP32 microcontroller, the device integrates multi-directional ultrasonic sensors for real-time obstacle detection, a tilt sensor for emergency fall/balance monitoring, and an audio buzzer alert mechanism. Developed custom embedded firmware in C++ and connected the system to the Blynk.io cloud platform for remote caregiver monitoring.",
          features: [
            "Real-Time Ultrasonic Obstacle Detection & Proximity Alert",
            "Tilt Sensor Integration for User Balance & Fall Detection",
            "Multi-frequency Audible Buzzer Warning System",
            "Custom Low-latency C++ Firmware Logic",
            "Blynk.io Cloud Dashboard for Remote Caregiver Status Monitoring",
          ],
          badge: "IoT Hardware",
        },
        {
          id: 4,
          title: "CryptoMania Cryptocurrency Platform",
          subtitle: "Live Market Analytics & Interactive Dashboard",
          category: "Web Development",
          tagCategory: "Web",
          period: "Mar 2025 - Jun 2025",
          description: "Real-time cryptocurrency analytics platform presenting market capitalization, price trajectories, and interactive statistics for the top 50 digital coins.",
          fullDescription: "CryptoMania is a full-featured, responsive cryptocurrency monitoring platform engineered with React.js and modern web standards. Built to consume the CoinGecko REST API with low latency, the platform provides real-time market valuations, historical performance charts, search and filter capabilities, and responsive UI components designed with Tailwind CSS and deployed on Vercel.",
          features: [
            "Real-Time Live Market Data via CoinGecko REST API",
            "Interactive Price Charts and Historical Data Visualization",
            "Smart Search & Top 50 Cryptocurrencies Filtering",
            "Fully Responsive Modern Web Interface with Tailwind CSS",
            "Optimized Performance & Production Deployment on Vercel",
          ],
          badge: "Live Web App",
        },
        {
          id: 5,
          title: "PMO Dynamic Analytics & Budget Dashboard",
          subtitle: "PT LEN Industri (Persero) Enterprise System",
          category: "Data & Dashboard",
          tagCategory: "Data",
          period: "Jun 2025 - Sept 2025",
          description: "Developed comprehensive dynamic dashboards using Google Looker Studio and AppSheet for real-time project management and budget oversight at PT LEN Industri.",
          fullDescription: "Engineered enterprise-grade project monitoring dashboards for PT LEN Industri (Persero). Designed to provide leadership with instant visibility into project milestones, resource expenditure, and budget tracking. Leveraged AppSheet for streamlined mobile/web data entry and Google Looker Studio for dynamic data visualization and executive reporting.",
          features: [
            "Real-Time Project Milestone Tracking & Budget Oversight",
            "Custom Automated Data Pipelines via AppSheet",
            "Interactive Dynamic Charts & KPI Cards in Looker Studio",
            "Structured Executive Management Reporting Documentation",
          ],
          badge: "Enterprise PMO",
        },
      ],
    },
    // Skills
    skills: {
      badge: "TECHNICAL REPERTOIRE",
      title: "Skills &",
      titleSpan: "Expertise",
      subtitle: "Structured overview of technical stacks, engineering tools, and programming languages honed through academic research, Capstone Design, and industry practice.",
    },
    // Certifications
    certs: {
      badge: "VERIFIED CREDENTIALS",
      title: "Licenses &",
      titleSpan: "Certifications",
      subtitle: "Professional certifications and recognized technical credentials in Deep Learning, Artificial Intelligence, Python, Data Science, and SQL.",
      list: [
        {
          title: "Deep Learning Specialization",
          issuer: "DeepLearning.AI",
          issueDate: "Aug 2026",
          validity: "Verified Credential",
          description: "Comprehensive deep learning foundations covering neural network architectures, optimization algorithms, and advanced modeling.",
        },
        {
          title: "Learn the Basics of AI (Belajar Dasar AI)",
          issuer: "Dicoding Indonesia",
          issueDate: "Nov 2024",
          validity: "Nov 2024 - Nov 2027",
          description: "Foundations of Artificial Intelligence, Machine Learning methodologies, and practical applications in modern industry.",
        },
        {
          title: "Getting Started with Python Programming",
          issuer: "Dicoding Indonesia",
          issueDate: "Nov 2024",
          validity: "Nov 2024 - Nov 2027",
          description: "Core Python fundamentals, object-oriented programming concepts, and standard data manipulation workflows.",
        },
        {
          title: "Learn the Basics of Data Science",
          issuer: "Dicoding Indonesia",
          issueDate: "Oct 2024",
          validity: "Oct 2024 - Oct 2027",
          description: "Data exploration, statistical thinking, preprocessing techniques, and structured analytical problem-solving.",
        },
        {
          title: "Learn the Basics of Structured Query Language (SQL)",
          issuer: "Dicoding Indonesia",
          issueDate: "Oct 2024",
          validity: "Oct 2024 - Oct 2027",
          description: "Relational database querying, schema structuring, aggregation functions, and database design fundamentals.",
        },
      ],
    },
    // Contact
    contact: {
      badge: "COMMUNICATION & INQUIRY",
      title: "Get In",
      titleSpan: "Touch",
      subtitle: "Open to engineering positions, technical collaborations, and research discussions. Feel free to send a message.",
      infoTitle: "Contact Information",
      emailLabel: "Email Address",
      phoneLabel: "WhatsApp / Direct Phone",
      locationLabel: "Current Location",
      locationVal: "Bekasi, West Java, Indonesia",
      affilLabel: "Academic Background",
      affilVal: "S1 Telecommunications Engineering (2022 - 2026)",
      socialTitle: "Professional Networks",
      formTitle: "Send a Direct Message",
      formSubtitle: "Fill in the form below and I will respond to your inquiry promptly.",
      nameLabel: "Your Full Name *",
      emailInputLabel: "Email Address *",
      subjectLabel: "Subject / Discussion Topic *",
      messageLabel: "Message *",
      namePlaceholder: "e.g. John Doe",
      emailPlaceholder: "john@company.com",
      subjectPlaceholder: "e.g. Engineering Role / Project Collaboration",
      messagePlaceholder: "Hello Raihan, I would like to discuss...",
      sendBtn: "Send Message",
      sending: "Sending Message...",
      successMsg: "✓ Thank you! Your message has been sent successfully.",
      errorMsg: "✕ Failed to send message. Please reach out directly via email or WhatsApp.",
    },
    // Footer
    footer: {
      degree: "S1 Telecommunications Engineering",
      rights: "All Rights Reserved.",
    },
  },

  id: {
    // Navbar
    nav: {
      home: "Beranda",
      about: "Tentang",
      experience: "Pengalaman",
      projects: "Proyek",
      skills: "Keahlian",
      certificates: "Sertifikat",
      contact: "Kontak",
      resume: "Resume / CV",
      portfolio: "PORTOFOLIO",
    },
    // Hero
    hero: {
      status: "Terbuka untuk Peluang Kerja",
      academic: "🎓 S1 Teknik Telekomunikasi",
      greeting: "Halo, Saya",
      specialization: "Computer Vision • Pengembangan IoT • Front-End Engineering",
      bio1: "Lulusan S1 Teknik Telekomunikasi dengan pengalaman praktis di bidang Edge AI, Computer Vision, serta magang industri di PT LEN Industri (Persero) dan HUMIC Engineering.",
      bio2: "Berpengalaman mengimplementasikan model edge YOLOv8 pada Raspberry Pi 5, merakit perangkat IoT ESP32, membuat dashboard dinamis Google Looker Studio, dan membangun aplikasi web modern React.",
      viewExperience: "Lihat Pengalaman & Karya",
      downloadCV: "Unduh CV Formal",
      getInTouch: "Hubungi Saya →",
      stats: {
        internships: { label: "Magang Industri", sub: "PT LEN & HUMIC" },
        projects: { label: "Proyek Unggulan", sub: "Edge AI • IoT • Web • Data" },
        certs: { label: "Sertifikasi", sub: "DeepLearning.AI & Dicoding" },
        specializations: { label: "Bidang Fokus", sub: "Computer Vision • IoT • Web" },
      },
    },
    // About
    about: {
      badge: "LATAR BELAKANG & PROFIL",
      title: "Tentang",
      titleSpan: "Saya",
      subtitle: "Lulusan Teknik Telekomunikasi dengan keahlian interdisipliner di bidang Computer Vision, sistem tertanam IoT, dan rekayasa Front-End.",
      profileTitle: "Profil Profesional",
      story1: "Saya adalah lulusan Teknik Telekomunikasi dengan fokus teknis mendalam yang menghubungkan perangkat keras tertanam, model computer vision cerdas di edge, serta antarmuka web dan mobile modern.",
      story2: "Selama masa studi, saya mengasah kemampuan praktis melalui asisten laboratorium di MBC Laboratory serta magang industri di PT LEN Industri (Persero) dan HUMIC Engineering.",
      story3: "Pada proyek Capstone Design, saya memimpin implementasi menyeluruh sistem edge computer vision penghitung manusia menggunakan YOLOv8n dan ByteTrack pada Raspberry Pi 5 terintegrasi Firebase dan aplikasi mobile Flutter.",
      higherEdu: "Pendidikan Tinggi",
      eduDegree: "S1 Teknik Telekomunikasi",
      eduPeriod: "2022 - 2026",
      eduDesc: "Fokus pada pengolahan sinyal digital, sistem tertanam (embedded systems), dasar jaringan telekomunikasi, dan integrasi kecerdasan buatan.",
      softSkillsTitle: "Etos Kerja & Soft Skills",
      softSkills: [
        { name: "Manajemen Waktu", desc: "Eksekusi deadline terstruktur & pelacakan sprint proyek" },
        { name: "Disiplin Tinggi", desc: "Standar riset dan penulisan kode berorientasi detail" },
        { name: "Adaptabilitas Cepat", desc: "Cepat mempelajari dan menguasai teknologi baru" },
        { name: "Kerja Sama Tim", desc: "Terbukti mampu berkoordinasi lintas laboratorium & tim" },
      ],
      pillarsTitle: "Bidang Keahlian Utama",
      pillars: [
        {
          title: "Computer Vision & Edge AI",
          description: "Deteksi objek YOLOv8, pelacakan multi-objek ByteTrack, deployment edge di Raspberry Pi 5 & optimasi inferensi FP16 PyTorch.",
        },
        {
          title: "Internet of Things (IoT)",
          description: "Pemrograman mikrokontroler (ESP32/Arduino) dengan integrasi sensor (Ultrasonik, Tilt, Buzzer) dan telemetri cloud Blynk.io.",
        },
        {
          title: "Front-End & Mobile Apps",
          description: "Pengembangan aplikasi web interaktif dan responsif dengan React.js & Tailwind CSS, serta aplikasi mobile monitoring dengan Flutter.",
        },
        {
          title: "PMO & Analisis Data",
          description: "Dashboard manajemen proyek korporat, pengawasan anggaran, dan otomatisasi proses kerja menggunakan Google Looker Studio & AppSheet.",
        },
      ],
    },
    // Experience
    experience: {
      badge: "LINIMASA KARIR & KEPEMIMPINAN",
      title: "Pengalaman",
      titleSpan: "Profesional",
      subtitle: "Rekam jejak terbukti dalam magang rekayasa industri, riset deep learning, instruktur laboratorium, dan organisasi kemahasiswaan.",
      tabWork: "💼 Magang Industri",
      tabOrg: "🏛️ Asisten Lab & Organisasi",
      workList: [
        {
          role: "Deep Learning Engineer, Internship",
          company: "HUMIC (Human Centric) Engineering",
          location: "Bandung, Indonesia",
          period: "Apr 2026 - Jul 2026",
          type: "Magang Riset Industri",
          highlights: [
            "Merancang dan mengimplementasikan arsitektur Deep Learning PyTorch (Multi-Branch 1D/2D CNN & BiLSTM-MHA) untuk deteksi depresi berbasis suara menggunakan dataset DAIC-WOZ (189 partisipan) dengan 5-Fold Stratified Cross-Validation ketat.",
            "Mengintegrasikan representasi fitur self-supervised (Wav2Vec 2.0 embedding 768 dimensi) dengan Mel-Spectrogram dan MFCC 120 dimensi ke dalam multi-modal feature fusion head.",
            "Mengatasi ketidakseimbangan kelas ekstrem (rasio 2.3:1) melalui custom optimizer AdamW, penjadwalan ReduceLROnPlateau, regularisasi dropout 0.4, dan penalti weighted Cross-Entropy Loss.",
            "Membangun pipeline Explainable AI (XAI) menggunakan SHAP GradientExplainer langsung pada lapisan fusi CNN untuk transparansi klinis atribusi fitur audio.",
          ],
          tags: ["PyTorch", "Wav2Vec 2.0", "BiLSTM-MHA", "SHAP XAI", "Audio Processing"],
        },
        {
          role: "Project Management Officer, Internship",
          company: "PT LEN Industri (Persero)",
          location: "Bandung, Indonesia",
          period: "Jun 2025 - Sept 2025",
          type: "Magang BUMN Industri Pertahanan",
          highlights: [
            "Mengembangkan dan mengelola dashboard proyek menggunakan Google Looker Studio untuk pemantauan proyek real-time yang dinamis dengan fokus utama pengawasan anggaran dan alokasi sumber daya.",
            "Memanfaatkan AppSheet dan Google Looker untuk mengotomatisasi dan mengoptimalkan alur proses manajemen proyek selama masa magang.",
            "Menyusun dan menstrukturkan berbagai dokumen manajemen proyek yang dibutuhkan untuk pelaporan manajemen eksekutif.",
          ],
          tags: ["Google Looker Studio", "AppSheet", "Project Management", "Budget Oversight", "Process Optimization"],
        },
      ],
      orgList: [
        {
          role: "Divisi Praktikum (Instruktur Laboratorium)",
          company: "MBC LABORATORY",
          location: "Fakultas Teknik Elektro",
          period: "2025 - 2026",
          type: "Asisten Laboratorium Akademik",
          highlights: [
            "Mengajar materi praktikum rekayasa teknis secara langsung kepada mahasiswa untuk memastikan pemahaman mendalam secara hands-on.",
            "Menyusun dan mengembangkan modul praktikum sebagai panduan teknis utama dalam proses pembelajaran mahasiswa.",
            "Menginstal dan mengonfigurasi lingkungan perangkat lunak teknis penting demi kelancaran kegiatan praktikum.",
            "Mengelola pemeliharaan fisik infrastruktur lab, tata letak workbench, dan manajemen kabel agar area praktikum aman dan kondusif.",
          ],
          tags: ["Pengajaran & Mentoring", "Penyusunan Modul", "Konfigurasi Sistem", "Manajemen Lab"],
        },
        {
          role: "Divisi Hubungan Masyarakat (Humas)",
          company: "TELERIUM",
          location: "Fakultas Teknik Elektro",
          period: "2023 - 2024",
          type: "Organisasi Departemen",
          highlights: [
            "Bertindak sebagai jembatan komunikasi utama dalam mengoordinasikan kegiatan lintas laboratorium di lingkungan Fakultas Teknik Elektro.",
            "Memastikan kelancaran arus informasi antara panitia penyelenggara dan asisten laboratorium guna meminimalkan hambatan teknis.",
          ],
          tags: ["Koordinasi Lintas Lab", "Humas Acara", "Komunikasi Stakeholder"],
        },
        {
          role: "Divisi Hubungan Masyarakat (Humas)",
          company: "PERMISI",
          location: "Bekasi",
          period: "2022 - 2023",
          type: "Organisasi Mahasiswa Daerah",
          highlights: [
            "Berperan aktif dalam tim proyek Education Roadshow yang menyasar berbagai sekolah menengah atas di wilayah Bekasi.",
            "Melaksanakan koordinasi intensif dan sosialisasi program secara langsung ke pihak sekolah untuk membangun hubungan kerja sama strategis.",
            "Mengelola komunikasi internal tim, penjadwalan presentasi, serta menghasilkan peningkatan nyata pada antusiasme peserta sosialisasi.",
          ],
          tags: ["Sosialisasi Pendidikan", "Public Speaking", "Koordinasi Tim", "Kerja Sama Mitra"],
        },
      ],
    },
    // Projects
    projects: {
      badge: "PORTOFOLIO TEKNIS",
      title: "Proyek",
      titleSpan: "Unggulan",
      subtitle: "Koleksi proyek rekayasa yang mencakup Computer Vision & Edge AI, sistem IoT, aplikasi web, dan dashboard korporat.",
      filters: {
        All: "Semua Proyek",
        AI: "🧠 Computer Vision & AI",
        IoT: "📡 IoT & Hardware",
        Web: "💻 Pengembangan Web",
        Data: "📊 Data & PMO",
      },
      viewDetails: "Lihat Detail →",
      modalOverview: "Ringkasan Proyek",
      modalHighlights: "Keunggulan & Arsitektur Utama",
      modalStack: "Teknologi & Stack",
      modalClose: "Tutup",
      modalLiveDemo: "Buka Aplikasi Live ↗",
      modalVideo: "Tonton Video Demo (YouTube) ↗",
      modalGitHub: "Repositori GitHub",
      list: [
        {
          id: 1,
          title: "Detectra: Edge Computer Vision People Counting",
          subtitle: "Proyek Capstone Design / Tugas Akhir",
          category: "Computer Vision & Edge AI",
          tagCategory: "AI",
          period: "2026",
          description: "Sistem pemantauan dan penghitungan manusia real-time berbasis YOLOv8n dan ByteTrack pada Raspberry Pi 5, terintegrasi Firebase RTDB dan aplikasi mobile Flutter.",
          fullDescription: "Proyek Capstone Design / Tugas Akhir Sarjana. Mengembangkan sistem edge AI otomatis untuk pemantauan okupansi dan penghitungan jumlah manusia pada Raspberry Pi 5 dengan Camera Module V2 IMX219 tanpa melakukan identifikasi biometrik/wajah demi menjaga privasi pengguna. Mengimplementasikan model YOLOv8n hasil fine-tuning (5.130 dataset citra, 81,41% mAP@0.5, 82,17% presisi, waktu inferensi ~146 ms / 6,84 FPS) yang dipadukan dengan pelacakan ByteTrack, logika garis virtual line-crossing berbasis centroid, filter anti-oscillation (cooldown 2 detik), dan spawn-side tracking. Membangun arsitektur distribusi data dua jalur asinkron: data numerik ke Firebase Realtime Database dan snapshot visual via Flask server lokal, dipantau melalui aplikasi mobile Detectra (Flutter) dengan akurasi pengujian sistem keseluruhan 90,23%.",
          features: [
            "Deteksi & Pelacakan Objek di Edge (YOLOv8n + ByteTrack Multi-Object Tracking)",
            "Logika Penghitungan Line-Crossing Centroid Dua Arah (Masuk / Keluar)",
            "Filter Anti-Oscillation (2s) & Spawn-Side Tracking untuk Mencegah Double Counting",
            "Arsitektur Data Dua Jalur Asinkron (Firebase Realtime DB + Local Flask Server)",
            "Aplikasi Mobile Detectra (Flutter) dengan Monitoring Real-time, Riwayat, & Remote Control RPi",
            "Akurasi Pengujian Keseluruhan 90,23% (Indoor & Outdoor) dengan Latensi Inferensi 146 ms",
          ],
          badge: "Capstone Project",
        },
        {
          id: 2,
          title: "Speech-Based Depression Detection AI",
          subtitle: "Magang Riset HUMIC Engineering",
          category: "AI & Deep Learning",
          tagCategory: "AI",
          period: "Apr 2026 - Jul 2026",
          description: "Merancang framework deep learning multi-cabang PyTorch (CNN & BiLSTM-MHA) dengan fusi fitur Wav2Vec 2.0 dan Explainable AI (SHAP) untuk deteksi depresi berbasis suara klinis.",
          fullDescription: "Proyek riset deep learning mutakhir yang dikembangkan di HUMIC (Human Centric) Engineering. Dibangun untuk mendeteksi tingkat keparahan depresi dari wawancara audio klinis (dataset DAIC-WOZ, 189 partisipan) di bawah validasi silang 5-Fold Stratified yang ketat. Mengintegrasikan representasi self-supervised Wav2Vec 2.0 (embedding 768 dimensi) dengan Mel-Spectrogram dan MFCC 120 dimensi ke dalam kepala fusi fitur multi-modal. Membangun pipeline Explainable AI menggunakan SHAP GradientExplainer untuk menginterpretasikan atribusi fitur audio secara transparan.",
          features: [
            "Arsitektur Multi-Branch 1D/2D CNN & BiLSTM-MHA",
            "Integrasi Representasi Pre-trained Wav2Vec 2.0 768 Dimensi",
            "Fusi Fitur Multi-Modal Deep Learning dengan Mel-Spectrogram & MFCC",
            "Mitigasi Imbalance Kelas Ekstrem (AdamW & Weighted Cross-Entropy Loss)",
            "Explainable AI (SHAP GradientExplainer) pada Lapisan Fusi CNN",
          ],
          badge: "Deep Learning AI",
        },
        {
          id: 3,
          title: "Alat Bantu Cerdas Tunanetra Berbasis ESP32",
          subtitle: "Integrasi Perangkat Keras IoT & Cloud",
          category: "IoT & Hardware",
          tagCategory: "IoT",
          period: "Mar 2025 - Jun 2025",
          description: "Merancang alat bantu navigasi tunanetra menggunakan mikrokontroler ESP32, sensor jarak ultrasonik, sensor kemiringan (tilt), alarm buzzer, dan platform IoT Blynk.io.",
          fullDescription: "Merancang dan memproduksi perangkat keras pintar portabel untuk meningkatkan keselamatan dan mobilitas pengguna tunanetra. Ditenagai mikrokontroler ESP32, perangkat ini mengintegrasikan sensor ultrasonik multi-arah untuk deteksi halangan secara real-time, sensor tilt untuk pemantauan keseimbangan/jatuh darurat, serta mekanisme alarm buzzer. Mengembangkan firmware tertanam dalam bahasa C++ dan menghubungkan sistem ke platform cloud Blynk.io untuk pemantauan jarak jauh oleh pendamping.",
          features: [
            "Deteksi Halangan Jarak Dekat & Peringatan Kedekatan Real-Time",
            "Integrasi Sensor Tilt untuk Deteksi Keseimbangan & Jatuh Pengguna",
            "Sistem Peringatan Buzzer Audio Multi-Frekuensi",
            "Logika Firmware C++ Kustom dengan Latensi Rendah",
            "Dashboard Cloud Blynk.io untuk Pemantauan Status Jarak Jauh",
          ],
          badge: "IoT Hardware",
        },
        {
          id: 4,
          title: "Platform Cryptocurrency CryptoMania",
          subtitle: "Analitik Pasar Real-Time & Dashboard Interaktif",
          category: "Pengembangan Web",
          tagCategory: "Web",
          period: "Mar 2025 - Jun 2025",
          description: "Platform analitik cryptocurrency real-time yang menyajikan kapitalisasi pasar, grafik pergerakan harga, dan statistik interaktif 50 koin teratas.",
          fullDescription: "CryptoMania adalah platform pemantauan cryptocurrency yang responsif dan berfitur lengkap yang dibangun menggunakan React.js dan standar web modern. Mengonsumsi REST API CoinGecko dengan latensi rendah, platform ini menyediakan data harga real-time, grafik riwayat interaktif, fitur pencarian dan filter cerdas, serta antarmuka responsif dengan Tailwind CSS yang dideploy di Vercel.",
          features: [
            "Data Pasar Real-Time melalui REST API CoinGecko",
            "Grafik Harga Interaktif dan Visualisasi Data Historis",
            "Pencarian Cerdas & Filter 50 Cryptocurrency Teratas",
            "Antarmuka Web Modern yang Responsif dengan Tailwind CSS",
            "Performa Cepat dan Deployment Produksi di Vercel",
          ],
          badge: "Live Web App",
        },
        {
          id: 5,
          title: "Dashboard Dinamis PMO & Anggaran Proyek",
          subtitle: "Sistem Manajemen Enterprise PT LEN Industri (Persero)",
          category: "Data & Dashboard",
          tagCategory: "Data",
          period: "Jun 2025 - Sept 2025",
          description: "Mengembangkan dashboard dinamis menggunakan Google Looker Studio dan AppSheet untuk pemantauan proyek dan pengawasan anggaran real-time di PT LEN Industri.",
          fullDescription: "Merancang dashboard pemantauan proyek tingkat enterprise untuk PT LEN Industri (Persero). Dirancang untuk memberikan visibilitas instan kepada pimpinan terkait milestone proyek, realisasi pengeluaran, dan pengawasan anggaran. Memanfaatkan AppSheet untuk input data terstruktur dari mobile/web dan Google Looker Studio untuk visualisasi data dinamis dan pelaporan eksekutif.",
          features: [
            "Pelacakan Milestone Proyek & Pengawasan Anggaran Real-Time",
            "Pipeline Otomatisasi Input Data Kustom via AppSheet",
            "Grafik Interaktif Dinamis & Kartu KPI di Looker Studio",
            "Penyusunan Dokumentasi Laporan Manajemen Eksekutif Terstruktur",
          ],
          badge: "Enterprise PMO",
        },
      ],
    },
    // Skills
    skills: {
      badge: "REPERTOAR TEKNIS",
      title: "Keahlian &",
      titleSpan: "Spesialisasi",
      subtitle: "Ikhtisar terstruktur teknologi, alat rekayasa, dan bahasa pemrograman yang diasah melalui riset akademik, proyek Capstone Design, dan praktik industri.",
    },
    // Certifications
    certs: {
      badge: "KREDENSIAL TERVERIFIKASI",
      title: "Lisensi &",
      titleSpan: "Sertifikasi",
      subtitle: "Sertifikasi profesional dan kredensial teknis resmi di bidang Deep Learning, Kecerdasan Buatan, Python, Data Science, dan SQL.",
      list: [
        {
          title: "Deep Learning Specialization",
          issuer: "DeepLearning.AI",
          issueDate: "Agu 2026",
          validity: "Kredensial Terverifikasi",
          description: "Fondasi deep learning komprehensif yang mencakup arsitektur jaringan saraf, algoritma optimasi, dan pemodelan tingkat lanjut.",
        },
        {
          title: "Belajar Dasar AI (Artificial Intelligence)",
          issuer: "Dicoding Indonesia",
          issueDate: "Nov 2024",
          validity: "Nov 2024 - Nov 2027",
          description: "Prinsip dasar Kecerdasan Buatan, metodologi Machine Learning, dan implementasi praktis di industri modern.",
        },
        {
          title: "Memulai Pemrograman dengan Python",
          issuer: "Dicoding Indonesia",
          issueDate: "Nov 2024",
          validity: "Nov 2024 - Nov 2027",
          description: "Dasar pemrograman Python, konsep berorientasi objek (OOP), dan alur manipulasi data standar.",
        },
        {
          title: "Belajar Dasar Data Science",
          issuer: "Dicoding Indonesia",
          issueDate: "Okt 2024",
          validity: "Okt 2024 - Okt 2027",
          description: "Eksplorasi data, pemikiran statistik, teknik pra-pemrosesan data, dan pemecahan masalah analitis terstruktur.",
        },
        {
          title: "Belajar Dasar Structured Query Language (SQL)",
          issuer: "Dicoding Indonesia",
          issueDate: "Okt 2024",
          validity: "Okt 2024 - Okt 2027",
          description: "Kueri database relasional, perancangan skema tabel, fungsi agregasi, dan dasar manajemen basis data.",
        },
      ],
    },
    // Contact
    contact: {
      badge: "KOMUNIKASI & PERTANYAAN",
      title: "Hubungi",
      titleSpan: "Saya",
      subtitle: "Terbuka untuk posisi rekayasa teknik, kolaborasi proyek, dan diskusi riset. Silakan kirimkan pesan.",
      infoTitle: "Informasi Kontak",
      emailLabel: "Alamat Email",
      phoneLabel: "WhatsApp / Telepon Langsung",
      locationLabel: "Lokasi Saat Ini",
      locationVal: "Bekasi, Jawa Barat, Indonesia",
      affilLabel: "Latar Belakang Akademik",
      affilVal: "S1 Teknik Telekomunikasi (2022 - 2026)",
      socialTitle: "Jaringan Profesional",
      formTitle: "Kirim Pesan Langsung",
      formSubtitle: "Isi formulir di bawah ini dan saya akan segera membalas pesan Anda.",
      nameLabel: "Nama Lengkap Anda *",
      emailInputLabel: "Alamat Email *",
      subjectLabel: "Topik / Subjek Pesan *",
      messageLabel: "Pesan *",
      namePlaceholder: "contoh: Budi Santoso",
      emailPlaceholder: "budi@perusahaan.com",
      subjectPlaceholder: "contoh: Peluang Kerja Rekayasa / Kolaborasi Proyek",
      messagePlaceholder: "Halo Raihan, saya ingin mendiskusikan tentang...",
      sendBtn: "Kirim Pesan",
      sending: "Mengirim Pesan...",
      successMsg: "✓ Terima kasih! Pesan Anda telah berhasil dikirim.",
      errorMsg: "✕ Gagal mengirim pesan. Silakan hubungi langsung via email atau WhatsApp.",
    },
    // Footer
    footer: {
      degree: "S1 Teknik Telekomunikasi",
      rights: "Hak Cipta Dilindungi.",
    },
  },
};

export const LanguageProvider = ({ children }) => {
  const [lang, setLang] = useState(() => {
    return localStorage.getItem("portfolio_lang") || "en";
  });

  const toggleLanguage = (selectedLang) => {
    setLang(selectedLang);
    localStorage.setItem("portfolio_lang", selectedLang);
  };

  const t = translations[lang] || translations.en;

  return (
    <LanguageContext.Provider value={{ lang, setLang: toggleLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);
