import React, { createContext, useContext, useState, useEffect } from "react";

const LanguageContext = createContext();

export const translations = {
  en: {
    // Navbar
    nav: {
      home: "Home",
      about: "About",
      experience: "Experience",
      projects: "Projects",
      skills: "Skills",
      certificates: "Certificates",
      contact: "Contact",
      resume: "Resume / CV",
      portfolio: "PORTFOLIO",
    },
    // Hero
    hero: {
      status: "Open for Opportunities",
      academic: "🎓 S1 Telecommunications Engineering",
      greeting: "Hi, I'm",
      specialization: "Internet of Things (IoT) • Front-End Development • Deep Learning",
      bio1: "Telecommunications Engineering graduate from Telkom University with strong interests in Internet of Things (IoT), Front-End Development, and Deep Learning.",
      bio2: "Gained practical experience through laboratory assistantship and industry internships at PT LEN Industri and HUMIC Engineering. Adaptable, a collaborative team player, and ready to contribute professionally to the technology industry.",
      viewExperience: "View Experience & Work",
      downloadCV: "Download Formal CV",
      getInTouch: "Get in Touch →",
      stats: {
        internships: { label: "Industry Internships", sub: "PT LEN & HUMIC" },
        projects: { label: "Featured Projects", sub: "Edge AI • IoT • Web • Data" },
        certs: { label: "Certifications", sub: "DeepLearning.AI & Dicoding" },
        specializations: { label: "Specializations", sub: "IoT • Front-End • Deep Learning" },
      },
    },
    // About
    about: {
      badge: "BACKGROUND & PROFILE",
      title: "About",
      titleSpan: "Me",
      subtitle: "Telecommunications Engineering graduate with practical experience in IoT systems, Front-End engineering, and Deep Learning research.",
      profileTitle: "Professional Profile",
      story1: "Telecommunications Engineering graduate from Telkom University with strong interests in Internet of Things (IoT), Front-End Development, and Deep Learning.",
      story2: "Gained practical experience through laboratory assistantship at MBC Laboratory and industry internships at PT LEN Industri and HUMIC Engineering.",
      story3: "Adaptable, a collaborative team player, and ready to contribute professionally to the technology industry.",
      higherEdu: "Higher Education",
      eduDegree: "S1 Telecommunications Engineering",
      eduPeriod: "2022 - 2026",
      eduDesc: "Focused on digital signal processing, embedded systems, network fundamentals, telecommunications systems, and artificial intelligence integration.",
      softSkillsTitle: "Core Soft Skills",
      softSkills: [
        { name: "Time Management", desc: "Structured deadline execution & sprint tracking" },
        { name: "Discipline", desc: "Detail-oriented research and code standards" },
        { name: "Adaptability", desc: "Rapid adoption of emerging tech stacks" },
        { name: "Teamwork", desc: "Proven cross-functional lab & team coordination" },
      ],
      pillarsTitle: "Areas of Expertise",
      pillars: [
        {
          title: "Deep Learning & Computer Vision",
          description: "PyTorch architectures (CNN, BiLSTM-MHA), YOLOv8 object detection, ByteTrack MOT, Wav2Vec 2.0 audio feature fusion & Explainable AI (SHAP).",
        },
        {
          title: "Internet of Things (IoT)",
          description: "ESP32 & Arduino development with multi-sensor integration (Ultrasonic, Tilt, Buzzer) and Blynk.io cloud telemetry.",
        },
        {
          title: "Front-End & Mobile Development",
          description: "Modern interactive web platforms using React.js, JavaScript, and CSS/Tailwind, and cross-platform mobile apps with Flutter.",
        },
        {
          title: "Data Analytics & Engineering Tools",
          description: "Enterprise project monitoring dashboards, budget oversight with Looker Studio & AppSheet, and Cisco Packet Tracer network configuration.",
        },
      ],
    },
    // Experience
    experience: {
      badge: "CAREER & LEADERSHIP TIMELINE",
      title: "Work & Organizational",
      titleSpan: "Experience",
      subtitle: "Proven track record in industrial engineering internships, deep learning research, laboratory instruction, and student leadership.",
      tabWork: "💼 Work Experience",
      tabOrg: "🏛️ Organizational & Lab",
      workList: [
        {
          role: "Deep Learning Engineer, Internship",
          company: "HUMIC (Human Centric) Engineering",
          location: "Bandung",
          period: "Apr 2026 - July 2026",
          type: "Industrial Research Internship",
          highlights: [
            "Designed and implemented PyTorch Deep Learning architectures (Multi-Branch 1D/2D CNN & BiLSTM-MHA) for speech-based depression detection using the DAIC-WOZ dataset (189 participants) under strict participant-level 5-Fold Stratified Cross-Validation.",
            "Integrated self-supervised pre-trained representations (Wav2Vec 2.0 768-dim embeddings) with Mel-Spectrograms and 120-dim MFCCs into a multi-modal deep feature fusion head.",
            "Mitigated severe class imbalance (2.3:1 ratio) through custom AdamW optimization, ReduceLROnPlateau scheduling, 0.4 dropout regularization, and weighted Cross-Entropy Loss penalties.",
            "Engineered Explainable AI (XAI) attribution pipelines leveraging SHAP GradientExplainer directly on CNN fusion layers to interpret spectral-temporal audio feature attributions for clinical transparency.",
            "Co-authored an IEEE-formatted research paper: \"A Comparative Study of Audio Feature Representations and Fusion Methods Across Machine Learning and Deep Learning for Depression Detection\".",
          ],
          tags: ["PyTorch", "Wav2Vec 2.0", "BiLSTM-MHA", "SHAP XAI", "Audio Processing", "IEEE Paper"],
        },
        {
          role: "Project Management Officer, Internship",
          company: "PT LEN Industri (Persero)",
          location: "Bandung",
          period: "Jun 2025 - Sept 2025",
          type: "BUMN Industry Internship",
          highlights: [
            "Developed and managed project dashboards using Google Looker Studio for dynamic, real-time project monitoring with a focus on budget oversight.",
            "Utilized AppSheet and Looker to optimize project management processes during the internship period.",
            "Prepared various project documents required for management reporting.",
          ],
          tags: ["Google Looker Studio", "AppSheet", "Project Management", "Budget Oversight", "Process Optimization"],
        },
      ],
      orgList: [
        {
          role: "Practicum Division",
          company: "MBC LABORATORY",
          location: "Faculty of Electrical Engineering",
          period: "2025 - 2026",
          type: "Laboratory Assistantship",
          highlights: [
            "Responsible for teaching practical material directly to students in the laboratory to ensure in-depth technical understanding.",
            "Compiling and developing practical modules as the main technical guide in the student learning process.",
            "Installing and configuring the necessary software to support the smooth running of practical activities.",
            "Managing the physical maintenance of the laboratory, including workbench layout and cable management, to ensure that the practical area remains safe and conducive.",
          ],
          tags: ["Teaching & Practicum", "Module Development", "Software Configuration", "Lab Maintenance"],
        },
        {
          role: "Public Relations Division",
          company: "TELERIUM",
          location: "Faculty of Electrical Engineering",
          period: "2023 - 2024",
          type: "Faculty Organization",
          highlights: [
            "Acting as a member who serves as the main communication bridge through intensive coordination between laboratories within the Faculty of Electrical Engineering.",
            "Ensuring the smooth flow of information between the organizers and laboratory assistants in order to minimize technical obstacles during the event.",
          ],
          tags: ["Cross-Lab Coordination", "Event PR", "Stakeholder Communication"],
        },
        {
          role: "Public Relations Division",
          company: "PERMISI",
          location: "Bekasi Area",
          period: "2022 - 2023",
          type: "Regional Student Organization",
          highlights: [
            "Actively participated as a team member in the Education Roadshow project targeting various high schools in the Bekasi area.",
            "Carried out intensive coordination and direct socialization of the program to schools to build and maintain strategic cooperative relationships.",
            "Managed internal team communication to ensure that activity schedules and presentation materials were delivered effectively and on time.",
            "Achievements: Successfully reached and increased the enthusiasm of high school students in Bekasi in learning about Telkom University's education programs through measurable outreach activities.",
          ],
          tags: ["Education Roadshow", "Public Relations", "Team Communication", "Strategic Partnerships"],
        },
      ],
    },
    // Projects
    projects: {
      badge: "TECHNICAL PORTFOLIO",
      title: "Featured",
      titleSpan: "Projects",
      subtitle: "Showcase of engineering projects spanning Computer Vision & Edge AI, IoT hardware systems, web applications, and enterprise dashboards.",
      filters: {
        All: "All Projects",
        AI: "🧠 Deep Learning & AI",
        IoT: "📡 IoT & Hardware",
        Web: "💻 Web Development",
        Data: "📊 Data & PMO",
      },
      viewDetails: "View Details →",
      modalOverview: "Project Overview",
      modalHighlights: "Key Highlights & Architecture",
      modalStack: "Technologies & Stack",
      modalClose: "Close",
      modalLiveDemo: "Launch Live Application ↗",
      modalVideo: "Watch Video Demo (YouTube) ↗",
      modalGitHub: "GitHub Repository",
      list: [
        {
          id: 1,
          title: "A Computer Vision-Based Human Monitoring and Counting System Using YOLOv8n and ByteTrack",
          subtitle: "Edge AI People Counting & Occupancy System (Capstone Design)",
          category: "Computer Vision & Edge AI",
          tagCategory: "AI",
          period: "Feb 2026 - Aug 2026",
          description: "Developed an edge AI human detection and counting system deployed on a Raspberry Pi 5 without personal identity recognition for user privacy.",
          fullDescription: "Developed an edge AI human detection and counting system deployed on a Raspberry Pi 5 without personal identity recognition for user privacy. Implemented YOLOv8n fine-tuned on a custom dataset (5,130 images, 81.41% mAP@0.5, 82.17% precision) and integrated ByteTrack with virtual line-crossing logic to prevent double-counting. Built an asynchronous dual-path distribution to Firebase Realtime Database and created the Detectra mobile app using Flutter for live monitoring, achieving 90.23% overall testing accuracy.",
          features: [
            "Edge AI Object Detection & Tracking (YOLOv8n + ByteTrack Multi-Object Tracking)",
            "Two-Way Virtual Line-Crossing Centroid Counting Logic to Prevent Double-Counting",
            "Privacy-Preserving Architecture Deployed on Raspberry Pi 5 without Identity Recognition",
            "Asynchronous Dual-Path Distribution to Firebase Realtime Database and Local Image Server",
            "Cross-Platform Detectra Mobile App Built with Flutter for Live Monitoring & Remote Control",
            "Overall System Testing Accuracy of 90.23% with 146 ms Real-Time Edge Inference",
          ],
          badge: "Capstone Project",
        },
        {
          id: 2,
          title: "Speech-Based Depression Detection AI",
          subtitle: "HUMIC Engineering Research Internship & IEEE Paper",
          category: "AI & Deep Learning",
          tagCategory: "AI",
          period: "Apr 2026 - July 2026",
          description: "Designed PyTorch Deep Learning architectures (Multi-Branch CNN & BiLSTM-MHA) with Wav2Vec 2.0 fusion and Explainable AI (SHAP) for clinical depression detection.",
          fullDescription: "Designed and implemented PyTorch Deep Learning architectures (Multi-Branch 1D/2D CNN & BiLSTM-MHA) for speech-based depression detection using the DAIC-WOZ dataset (189 participants) under strict participant-level 5-Fold Stratified Cross-Validation. Integrated self-supervised pre-trained representations (Wav2Vec 2.0 768-dim embeddings) with Mel-Spectrograms and 120-dim MFCCs into a multi-modal deep feature fusion head. Mitigated severe class imbalance (2.3:1 ratio) through custom AdamW optimization, ReduceLROnPlateau scheduling, 0.4 dropout regularization, and weighted Cross-Entropy Loss penalties. Engineered Explainable AI (XAI) attribution pipelines leveraging SHAP GradientExplainer directly on CNN fusion layers. Co-authored an IEEE-formatted research paper: 'A Comparative Study of Audio Feature Representations and Fusion Methods Across Machine Learning and Deep Learning for Depression Detection'.",
          features: [
            "Multi-Branch 1D/2D CNN & BiLSTM-MHA Deep Learning Architecture in PyTorch",
            "Integrated Pre-Trained Wav2Vec 2.0 (768-dim) with Mel-Spectrograms & MFCCs (120-dim)",
            "Participant-Level 5-Fold Stratified Cross-Validation on DAIC-WOZ Dataset",
            "Severe Class Imbalance Mitigation (AdamW Optimization & Weighted Cross-Entropy Loss)",
            "Explainable AI (SHAP GradientExplainer) on CNN Fusion Layers for Clinical Transparency",
            "Co-authored IEEE-Formatted Audio Feature Representation & Fusion Research Paper",
          ],
          badge: "Deep Learning AI",
        },
        {
          id: 3,
          title: "ESP32 Based Smart Assistive Device for the Visually Impaired",
          subtitle: "IoT Embedded Navigation & Sensor System",
          category: "IoT & Hardware",
          tagCategory: "IoT",
          period: "Mar 2025 - Jun 2025",
          description: "Designed a navigation aid for the visually impaired using an ESP32 microcontroller, ultrasonic sensors, tilt sensor, buzzer alarm, and Blynk.io platform.",
          fullDescription: "Designed a navigation aid for the visually impaired using an ESP32 microcontroller to enhance user safety and mobility. Integrated ultrasonic sensors for obstacle detection, a tilt sensor for balance monitoring, and a buzzer alarm system. Developed device logic using C++ and integrated it with the Blynk.io platform for monitoring functionality.",
          features: [
            "Navigation Aid for Visually Impaired to Enhance User Safety and Mobility",
            "ESP32 Microcontroller Embedded Processing & Logic in C++",
            "Ultrasonic Sensors Integration for Real-Time Proximity & Obstacle Detection",
            "Tilt Sensor Integration for User Balance & Fall Emergency Monitoring",
            "Audible Buzzer Warning Alarm System",
            "Cloud Platform Integration with Blynk.io for Caregiver Telemetry & Monitoring",
          ],
          badge: "IoT Hardware",
        },
        {
          id: 4,
          title: "CryptoMania Website Development",
          subtitle: "Live Cryptocurrency Information & Analytics Platform",
          category: "Web Development",
          tagCategory: "Web",
          period: "Mar 2025 - Jun 2025",
          description: "Built a cryptocurrency information platform providing real-time data on coin names, market values, descriptions, and price history using React.js.",
          fullDescription: "Built a cryptocurrency information platform providing real-time data on coin names, market values, descriptions, and price history. Led the front-end development using React.js, JavaScript, and CSS. Designed and implemented a responsive user interface to present data for the top 50 coins informatively.",
          features: [
            "Real-Time Data on Coin Names, Market Values, Descriptions, and Price History",
            "Led Front-End Development Using React.js, JavaScript, and CSS",
            "Responsive User Interface Presenting Top 50 Cryptocurrencies Informatively",
            "Live REST API Integration with Fast Asynchronous Data Ingestion",
            "Production Web Deployment on Vercel Platform",
          ],
          badge: "Live Web App",
        },
        {
          id: 5,
          title: "Project Management & Budget Oversight Dashboard",
          subtitle: "PT LEN Industri (Persero) PMO Enterprise System",
          category: "Data & Dashboard",
          tagCategory: "Data",
          period: "Jun 2025 - Sept 2025",
          description: "Developed dynamic project dashboards using Google Looker Studio and AppSheet for real-time project monitoring with a focus on budget oversight at PT LEN Industri.",
          fullDescription: "Developed and managed project dashboards using Google Looker Studio for dynamic, real-time project monitoring with a focus on budget oversight at PT LEN Industri (Persero). Utilized AppSheet and Looker to optimize project management processes during the internship period. Prepared various project documents required for management reporting.",
          features: [
            "Dynamic Real-Time Project Dashboards in Google Looker Studio",
            "Focused Budget Oversight, Resource Tracking & Milestone Analytics",
            "Process Optimization and Mobile Data Ingestion via AppSheet",
            "Structured Project Management Reporting for Executive Review",
          ],
          badge: "Enterprise PMO",
        },
      ],
    },
    // Skills
    skills: {
      badge: "TECH STACK & HARD SKILLS",
      title: "Hard Skills &",
      titleSpan: "Expertise",
      subtitle: "Comprehensive overview of technical capabilities, programming languages, and tools from academic education, research, and industry experience.",
    },
    // Certifications
    certs: {
      badge: "VERIFIED CREDENTIALS",
      title: "Licenses &",
      titleSpan: "Certifications",
      subtitle: "Professional certifications and recognized credentials in Deep Learning, Artificial Intelligence, Python, Data Science, and SQL.",
      list: [
        {
          title: "Deep Learning",
          issuer: "DeepLearning.AI",
          issueDate: "Aug 2026",
          validity: "Aug 2026",
          description: "Comprehensive neural network architectures, multi-layer optimization, hyperparameter tuning, and deep learning engineering.",
        },
        {
          title: "Learn the Basics of AI (Belajar Dasar AI)",
          issuer: "Dicoding Indonesia",
          issueDate: "Nov 2024",
          validity: "Nov 2024 - Nov 2027",
          description: "Foundational principles of Artificial Intelligence, Machine Learning workflows, and intelligent system implementations.",
        },
        {
          title: "Getting Started with Python Programming (Memulai Pemrograman dengan Python)",
          issuer: "Dicoding Indonesia",
          issueDate: "Nov 2024",
          validity: "Nov 2024 - Nov 2027",
          description: "Python language syntax, functional constructs, object-oriented programming (OOP), and structured data handling.",
        },
        {
          title: "Learn the Basics of Data Science (Belajar Dasar Data Science)",
          issuer: "Dicoding Indonesia",
          issueDate: "Oct 2024",
          validity: "Oct 2024 - Oct 2027",
          description: "Data exploration, statistical analysis, feature engineering, data preprocessing, and analytical problem-solving.",
        },
        {
          title: "Learn the Basics of Structured Query Language (SQL)",
          issuer: "Dicoding Indonesia",
          issueDate: "Oct 2024",
          validity: "Oct 2024 - Oct 2027",
          description: "Relational database architecture, data manipulation queries, aggregation functions, and database design fundamentals.",
        },
      ],
    },
    // Contact
    contact: {
      badge: "COMMUNICATION & INQUIRY",
      title: "Get In",
      titleSpan: "Touch",
      subtitle: "Open to engineering positions, technical collaborations, and research discussions. Feel free to send a message.",
      infoTitle: "Contact Information",
      emailLabel: "Email Address",
      phoneLabel: "WhatsApp / Direct Phone",
      locationLabel: "Current Location",
      locationVal: "Bekasi, West Java, Indonesia",
      affilLabel: "Academic Background",
      affilVal: "S1 Telecommunications Engineering, Telkom University",
      socialTitle: "Professional Networks",
      formTitle: "Send a Direct Message",
      formSubtitle: "Fill in the form below and I will respond to your inquiry promptly.",
      nameLabel: "Your Full Name *",
      emailInputLabel: "Email Address *",
      subjectLabel: "Subject / Discussion Topic *",
      messageLabel: "Message *",
      namePlaceholder: "e.g. John Doe",
      emailPlaceholder: "john@company.com",
      subjectPlaceholder: "e.g. Engineering Role / Project Collaboration",
      messagePlaceholder: "Hello Raihan, I would like to discuss...",
      sendBtn: "Send Message",
      sending: "Sending Message...",
      successMsg: "✓ Thank you! Your message has been sent successfully.",
      errorMsg: "✕ Failed to send message. Please reach out directly via email or WhatsApp.",
    },
    // Footer
    footer: {
      degree: "S1 Telecommunications Engineering - Telkom University",
      rights: "All Rights Reserved.",
    },
  },

  id: {
    // Navbar
    nav: {
      home: "Beranda",
      about: "Tentang",
      experience: "Pengalaman",
      projects: "Proyek",
      skills: "Keahlian",
      certificates: "Sertifikat",
      contact: "Kontak",
      resume: "Resume / CV",
      portfolio: "PORTOFOLIO",
    },
    // Hero
    hero: {
      status: "Terbuka untuk Peluang Kerja",
      academic: "🎓 S1 Teknik Telekomunikasi - Telkom University",
      greeting: "Halo, Saya",
      specialization: "Internet of Things (IoT) • Front-End Development • Deep Learning",
      bio1: "Lulusan S1 Teknik Telekomunikasi dari Telkom University dengan minat mendalam pada Internet of Things (IoT), Front-End Development, dan Deep Learning.",
      bio2: "Memperoleh pengalaman praktis melalui asisten laboratorium serta magang industri di PT LEN Industri dan HUMIC Engineering. Adaptif, komunikatif dalam kerja tim, dan siap berkontribusi secara profesional di industri teknologi.",
      viewExperience: "Lihat Pengalaman & Karya",
      downloadCV: "Unduh CV Formal",
      getInTouch: "Hubungi Saya →",
      stats: {
        internships: { label: "Magang Industri", sub: "PT LEN & HUMIC" },
        projects: { label: "Proyek Unggulan", sub: "Edge AI • IoT • Web • Data" },
        certs: { label: "Sertifikasi", sub: "DeepLearning.AI & Dicoding" },
        specializations: { label: "Bidang Fokus", sub: "IoT • Front-End • Deep Learning" },
      },
    },
    // About
    about: {
      badge: "LATAR BELAKANG & PROFIL",
      title: "Tentang",
      titleSpan: "Saya",
      subtitle: "Lulusan Teknik Telekomunikasi dengan pengalaman praktis dalam sistem IoT, rekayasa Front-End, dan riset Deep Learning.",
      profileTitle: "Profil Profesional",
      story1: "Lulusan S1 Teknik Telekomunikasi dari Telkom University dengan minat mendalam pada Internet of Things (IoT), Front-End Development, dan Deep Learning.",
      story2: "Memperoleh pengalaman praktis melalui asisten laboratorium di MBC Laboratory serta magang industri di PT LEN Industri dan HUMIC Engineering.",
      story3: "Adaptif, komunikatif dalam kerja tim, dan siap berkontribusi secara profesional di industri teknologi.",
      higherEdu: "Pendidikan Tinggi",
      eduDegree: "S1 Teknik Telekomunikasi",
      eduPeriod: "2022 - 2026",
      eduDesc: "Fokus pada pengolahan sinyal digital, sistem tertanam (embedded systems), dasar jaringan telekomunikasi, dan integrasi kecerdasan buatan.",
      softSkillsTitle: "Soft Skills Utama",
      softSkills: [
        { name: "Time Management", desc: "Manajemen waktu terstruktur & eksekusi deadline" },
        { name: "Discipline", desc: "Disiplin tinggi pada standar riset dan kode" },
        { name: "Adaptability", desc: "Kemampuan adaptasi cepat dengan teknologi baru" },
        { name: "Teamwork", desc: "Kerja sama tim dan koordinasi lintas laboratorium" },
      ],
      pillarsTitle: "Bidang Keahlian Utama",
      pillars: [
        {
          title: "Deep Learning & Computer Vision",
          description: "Arsitektur PyTorch (CNN, BiLSTM-MHA), deteksi objek YOLOv8, pelacakan ByteTrack MOT, fusi fitur audio Wav2Vec 2.0 & Explainable AI (SHAP).",
        },
        {
          title: "Internet of Things (IoT)",
          description: "Pengembangan mikrokontroler Arduino & ESP32, integrasi multi-sensor (Ultrasonik, Kemiringan/Tilt, Buzzer) dan telemetri platform Blynk.io.",
        },
        {
          title: "Front-End & Mobile Development",
          description: "Aplikasi web modern interaktif berbasis React.js, JavaScript, dan CSS/Tailwind, serta aplikasi mobile monitoring berbasis Flutter.",
        },
        {
          title: "Data Analytics & Engineering Tools",
          description: "Dashboard dinamis Looker Studio & AppSheet untuk pengawasan anggaran proyek, kueri database SQL, dan konfigurasi jaringan Cisco Packet Tracer.",
        },
      ],
    },
    // Experience
    experience: {
      badge: "LINIMASA KARIR & KEPEMIMPINAN",
      title: "Pengalaman Kerja &",
      titleSpan: "Organisasi",
      subtitle: "Rekam jejak terbukti dalam magang rekayasa industri, riset deep learning, instruktur laboratorium, dan kepemimpinan kemahasiswaan.",
      tabWork: "💼 Pengalaman Kerja",
      tabOrg: "🏛️ Organisasi & Asisten Lab",
      workList: [
        {
          role: "Deep Learning Engineer, Internship",
          company: "HUMIC (Human Centric) Engineering",
          location: "Bandung",
          period: "Apr 2026 - July 2026",
          type: "Magang Riset Industri",
          highlights: [
            "Merancang dan mengimplementasikan arsitektur Deep Learning PyTorch (Multi-Branch 1D/2D CNN & BiLSTM-MHA) untuk deteksi depresi berbasis suara menggunakan dataset DAIC-WOZ (189 partisipan) di bawah 5-Fold Stratified Cross-Validation ketat.",
            "Mengintegrasikan representasi self-supervised pre-trained (Wav2Vec 2.0 embedding 768 dimensi) dengan Mel-Spectrogram dan MFCC 120 dimensi ke dalam multi-modal deep feature fusion head.",
            "Mengatasi ketidakseimbangan kelas ekstrem (rasio 2.3:1) melalui custom optimizer AdamW, penjadwalan ReduceLROnPlateau, regularisasi dropout 0.4, dan penalti weighted Cross-Entropy Loss.",
            "Membangun pipeline Explainable AI (XAI) memanfaatkan SHAP GradientExplainer langsung pada lapisan fusi CNN untuk transparansi klinis atribusi fitur audio spektral-temporal.",
            "Menulis bersama (co-author) makalah riset berformat IEEE: \"A Comparative Study of Audio Feature Representations and Fusion Methods Across Machine Learning and Deep Learning for Depression Detection\".",
          ],
          tags: ["PyTorch", "Wav2Vec 2.0", "BiLSTM-MHA", "SHAP XAI", "Audio Processing", "IEEE Paper"],
        },
        {
          role: "Project Management Officer, Internship",
          company: "PT LEN Industri (Persero)",
          location: "Bandung",
          period: "Jun 2025 - Sept 2025",
          type: "Magang Industri BUMN",
          highlights: [
            "Mengembangkan dan mengelola dashboard proyek menggunakan Google Looker Studio untuk pemantauan proyek real-time dinamis dengan fokus pengawasan anggaran (budget oversight).",
            "Memanfaatkan AppSheet dan Looker untuk mengoptimalkan proses manajemen proyek selama masa magang.",
            "Menyiapkan berbagai dokumen proyek yang dibutuhkan untuk pelaporan manajemen eksekutif.",
          ],
          tags: ["Google Looker Studio", "AppSheet", "Project Management", "Budget Oversight", "Process Optimization"],
        },
      ],
      orgList: [
        {
          role: "Practicum Division",
          company: "MBC LABORATORY",
          location: "Fakultas Teknik Elektro",
          period: "2025 - 2026",
          type: "Asisten Laboratorium",
          highlights: [
            "Bertanggung jawab mengajar materi praktikum secara langsung kepada mahasiswa di laboratorium untuk memastikan pemahaman teknis mendalam.",
            "Menyusun dan mengembangkan modul praktikum sebagai panduan teknis utama dalam proses pembelajaran mahasiswa.",
            "Menginstal dan mengonfigurasi perangkat lunak yang diperlukan untuk kelancaran kegiatan praktikum.",
            "Mengelola pemeliharaan fisik laboratorium, tata letak workbench, dan manajemen kabel untuk memastikan area praktikum tetap aman dan kondusif.",
          ],
          tags: ["Pengajaran & Praktikum", "Penyusunan Modul", "Konfigurasi Software", "Pemeliharaan Lab"],
        },
        {
          role: "Public Relations Division",
          company: "TELERIUM",
          location: "Fakultas Teknik Elektro",
          period: "2023 - 2024",
          type: "Organisasi Fakultas",
          highlights: [
            "Bertindak sebagai anggota yang menjadi jembatan komunikasi utama melalui koordinasi intensif antar laboratorium di lingkungan Fakultas Teknik Elektro.",
            "Memastikan kelancaran arus informasi antara panitia penyelenggara dan asisten laboratorium guna meminimalkan kendala teknis selama acara.",
          ],
          tags: ["Koordinasi Antar Lab", "Humas Acara", "Komunikasi Stakeholder"],
        },
        {
          role: "Public Relations Division",
          company: "PERMISI",
          location: "Wilayah Bekasi",
          period: "2022 - 2023",
          type: "Organisasi Mahasiswa Daerah",
          highlights: [
            "Berperan aktif sebagai anggota tim dalam proyek Education Roadshow yang menyasar berbagai sekolah menengah atas di wilayah Bekasi.",
            "Melaksanakan koordinasi intensif dan sosialisasi program secara langsung ke pihak sekolah untuk membangun dan menjaga hubungan kerja sama strategis.",
            "Mengelola komunikasi internal tim untuk memastikan jadwal kegiatan dan materi presentasi tersampaikan secara efektif dan tepat waktu.",
            "Pencapaian (Achievements): Berhasil menjangkau dan meningkatkan antusiasme siswa SMA di Bekasi dalam mengenal program pendidikan Telkom University melalui kegiatan sosialisasi yang terukur.",
          ],
          tags: ["Education Roadshow", "Hubungan Masyarakat", "Komunikasi Tim", "Kemitraan Strategis"],
        },
      ],
    },
    // Projects
    projects: {
      badge: "PORTOFOLIO TEKNIS",
      title: "Proyek",
      titleSpan: "Unggulan",
      subtitle: "Koleksi proyek rekayasa yang mencakup Computer Vision & Edge AI, sistem perangkat keras IoT, aplikasi web, dan dashboard manajemen proyek.",
      filters: {
        All: "Semua Proyek",
        AI: "🧠 Deep Learning & AI",
        IoT: "📡 IoT & Hardware",
        Web: "💻 Pengembangan Web",
        Data: "📊 Data & PMO",
      },
      viewDetails: "Lihat Detail →",
      modalOverview: "Ringkasan Proyek",
      modalHighlights: "Keunggulan & Arsitektur Utama",
      modalStack: "Teknologi & Stack",
      modalClose: "Tutup",
      modalLiveDemo: "Buka Aplikasi Live ↗",
      modalVideo: "Tonton Video Demo (YouTube) ↗",
      modalGitHub: "Repositori GitHub",
      list: [
        {
          id: 1,
          title: "A Computer Vision-Based Human Monitoring and Counting System Using YOLOv8n and ByteTrack",
          subtitle: "Sistem Pemantauan & Penghitung Manusia Edge AI (Capstone Design)",
          category: "Computer Vision & Edge AI",
          tagCategory: "AI",
          period: "Feb 2026 - Aug 2026",
          description: "Mengembangkan sistem edge AI deteksi dan penghitungan manusia yang dideploy pada Raspberry Pi 5 tanpa pengenalan identitas pribadi untuk menjaga privasi pengguna.",
          fullDescription: "Mengembangkan sistem edge AI deteksi dan penghitungan manusia yang dideploy pada Raspberry Pi 5 tanpa pengenalan identitas pribadi untuk menjaga privasi pengguna. Mengimplementasikan YOLOv8n hasil fine-tuning pada custom dataset (5.130 citra, 81,41% mAP@0.5, 82,17% presisi) dan mengintegrasikan ByteTrack dengan logika virtual line-crossing untuk mencegah double-counting. Membangun distribusi data dua jalur asinkron ke Firebase Realtime Database dan aplikasi mobile Detectra menggunakan Flutter untuk live monitoring, dengan akurasi pengujian sistem keseluruhan 90,23%.",
          features: [
            "Deteksi & Pelacakan Objek Edge AI (YOLOv8n + Pelacakan Multi-Objek ByteTrack)",
            "Logika Penghitungan Centroid Virtual Line-Crossing Dua Arah untuk Mencegah Double-Counting",
            "Arsitektur Penjaga Privasi Dideploy pada Raspberry Pi 5 Tanpa Pengenalan Identitas Wajah",
            "Distribusi Data Dua Jalur Asinkron ke Firebase Realtime Database & Server Citra Lokal",
            "Aplikasi Mobile Detectra Dibangun dengan Flutter untuk Live Monitoring & Kontrol RPi",
            "Akurasi Pengujian Keseluruhan 90,23% dengan Latensi Inferensi Real-Time 146 ms",
          ],
          badge: "Capstone Project",
        },
        {
          id: 2,
          title: "Speech-Based Depression Detection AI",
          subtitle: "Magang Riset HUMIC Engineering & Makalah IEEE",
          category: "AI & Deep Learning",
          tagCategory: "AI",
          period: "Apr 2026 - July 2026",
          description: "Merancang arsitektur Deep Learning PyTorch (Multi-Branch CNN & BiLSTM-MHA) dengan fusi Wav2Vec 2.0 dan Explainable AI (SHAP) untuk deteksi depresi klinis berbasis suara.",
          fullDescription: "Merancang dan mengimplementasikan arsitektur Deep Learning PyTorch (Multi-Branch 1D/2D CNN & BiLSTM-MHA) untuk deteksi depresi berbasis suara menggunakan dataset DAIC-WOZ (189 partisipan) di bawah 5-Fold Stratified Cross-Validation ketat. Mengintegrasikan representasi self-supervised pre-trained (Wav2Vec 2.0 embedding 768 dimensi) dengan Mel-Spectrogram dan MFCC 120 dimensi ke dalam multi-modal deep feature fusion head. Mengatasi ketidakseimbangan kelas ekstrem (rasio 2.3:1) melalui custom optimizer AdamW, penjadwalan ReduceLROnPlateau, regularisasi dropout 0.4, dan penalti weighted Cross-Entropy Loss. Membangun pipeline Explainable AI (XAI) memanfaatkan SHAP GradientExplainer langsung pada lapisan fusi CNN. Menulis bersama (co-author) makalah riset berformat IEEE: 'A Comparative Study of Audio Feature Representations and Fusion Methods Across Machine Learning and Deep Learning for Depression Detection'.",
          features: [
            "Arsitektur Multi-Branch 1D/2D CNN & BiLSTM-MHA Deep Learning di PyTorch",
            "Integrasi Pre-Trained Wav2Vec 2.0 (768 dimensi) dengan Mel-Spectrogram & MFCC (120 dimensi)",
            "5-Fold Stratified Cross-Validation Tingkat Partisipan pada Dataset DAIC-WOZ",
            "Mitigasi Ketidakseimbangan Kelas Ekstrem (Optimasi AdamW & Weighted Cross-Entropy Loss)",
            "Explainable AI (SHAP GradientExplainer) pada Lapisan Fusi CNN untuk Transparansi Klinis",
            "Co-authored Makalah Riset Berformat IEEE untuk Representasi & Fusi Fitur Audio",
          ],
          badge: "Deep Learning AI",
        },
        {
          id: 3,
          title: "ESP32 Based Smart Assistive Device for the Visually Impaired",
          subtitle: "Sistem Navigasi & Sensor Tertanam IoT",
          category: "IoT & Hardware",
          tagCategory: "IoT",
          period: "Mar 2025 - Jun 2025",
          description: "Merancang alat bantu navigasi tunanetra menggunakan mikrokontroler ESP32, sensor ultrasonik, sensor kemiringan (tilt), alarm buzzer, dan platform Blynk.io.",
          fullDescription: "Merancang alat bantu navigasi untuk penyandang tunanetra menggunakan mikrokontroler ESP32 untuk meningkatkan keselamatan dan mobilitas pengguna. Mengintegrasikan sensor ultrasonik untuk deteksi rintangan/halangan, sensor kemiringan (tilt) untuk pemantauan keseimbangan, dan sistem alarm buzzer. Mengembangkan logika perangkat menggunakan C++ dan mengintegrasikannya dengan platform Blynk.io untuk fungsionalitas pemantauan.",
          features: [
            "Alat Bantu Navigasi Tunanetra untuk Meningkatkan Keselamatan & Mobilitas Pengguna",
            "Pemrosesan Tertanam & Logika Mikrokontroler ESP32 Menggunakan C++",
            "Integrasi Sensor Ultrasonik untuk Deteksi Jarak & Rintangan Real-Time",
            "Integrasi Sensor Tilt untuk Pemantauan Keseimbangan & Jatuh Darurat",
            "Sistem Peringatan Alarm Buzzer Audio",
            "Integrasi Platform Cloud Blynk.io untuk Pemantauan Status & Telemetri Jarak Jauh",
          ],
          badge: "IoT Hardware",
        },
        {
          id: 4,
          title: "CryptoMania Website Development",
          subtitle: "Platform Informasi & Analitik Cryptocurrency Real-Time",
          category: "Pengembangan Web",
          tagCategory: "Web",
          period: "Mar 2025 - Jun 2025",
          description: "Membangun platform informasi cryptocurrency yang menyediakan data real-time nama koin, nilai pasar, deskripsi, dan riwayat harga menggunakan React.js.",
          fullDescription: "Membangun platform informasi cryptocurrency yang menyediakan data real-time tentang nama koin, nilai pasar, deskripsi, dan riwayat harga. Memimpin pengembangan front-end menggunakan React.js, JavaScript, dan CSS. Merancang dan mengimplementasikan antarmuka pengguna yang responsif untuk menyajikan data 50 koin teratas secara informatif.",
          features: [
            "Data Real-Time Nama Koin, Nilai Pasar, Deskripsi, dan Riwayat Harga",
            "Memimpin Pengembangan Front-End Menggunakan React.js, JavaScript, dan CSS",
            "Antarmuka Pengguna Responsif Menyajikan 50 Cryptocurrency Teratas",
            "Integrasi REST API Langsung dengan Pengambilan Data Asinkron Cepat",
            "Deployment Produksi Web pada Platform Vercel",
          ],
          badge: "Live Web App",
        },
        {
          id: 5,
          title: "Project Management & Budget Oversight Dashboard",
          subtitle: "Sistem Enterprise PMO PT LEN Industri (Persero)",
          category: "Data & Dashboard",
          tagCategory: "Data",
          period: "Jun 2025 - Sept 2025",
          description: "Mengembangkan dan mengelola dashboard proyek menggunakan Google Looker Studio dan AppSheet untuk pemantauan proyek real-time dengan fokus pengawasan anggaran di PT LEN Industri.",
          fullDescription: "Mengembangkan dan mengelola dashboard proyek menggunakan Google Looker Studio untuk pemantauan proyek real-time yang dinamis dengan fokus pengawasan anggaran di PT LEN Industri (Persero). Memanfaatkan AppSheet dan Looker untuk mengoptimalkan proses manajemen proyek selama masa magang. Menyiapkan berbagai dokumen proyek yang dibutuhkan untuk pelaporan manajemen.",
          features: [
            "Dashboard Proyek Dinamis Real-Time di Google Looker Studio",
            "Fokus Pengawasan Anggaran (Budget Oversight), Pelacakan Sumber Daya & Milestone",
            "Optimalisasi Proses dan Input Data Mobile melalui AppSheet",
            "Penyusunan Berbagai Dokumen Proyek untuk Pelaporan Manajemen Eksekutif",
          ],
          badge: "Enterprise PMO",
        },
      ],
    },
    // Skills
    skills: {
      badge: "KEAHLIAN TEKNIS & HARD SKILLS",
      title: "Hard Skills &",
      titleSpan: "Spesialisasi",
      subtitle: "Ikhtisar komprehensif keahlian teknis, bahasa pemrograman, dan tools dari pendidikan akademik, riset, serta pengalaman industri.",
    },
    // Certifications
    certs: {
      badge: "KREDENSIAL TERVERIFIKASI",
      title: "Lisensi &",
      titleSpan: "Sertifikasi",
      subtitle: "Sertifikasi profesional dan kredensial resmi di bidang Deep Learning, Kecerdasan Buatan, Python, Data Science, dan SQL.",
      list: [
        {
          title: "Deep Learning",
          issuer: "DeepLearning.AI",
          issueDate: "Agu 2026",
          validity: "Agu 2026",
          description: "Arsitektur jaringan saraf mendalam, optimasi multi-layer, hyperparameter tuning, dan rekayasa deep learning terapan.",
        },
        {
          title: "Learn the Basics of AI (Belajar Dasar AI)",
          issuer: "Dicoding Indonesia",
          issueDate: "Nov 2024",
          validity: "Nov 2024 - Nov 2027",
          description: "Prinsip dasar Kecerdasan Buatan, alur kerja Machine Learning, dan implementasi sistem cerdas.",
        },
        {
          title: "Getting Started with Python Programming (Memulai Pemrograman dengan Python)",
          issuer: "Dicoding Indonesia",
          issueDate: "Nov 2024",
          validity: "Nov 2024 - Nov 2027",
          description: "Sintaks bahasa Python, konstruksi fungsional, pemrograman berorientasi objek (OOP), dan manipulasi data terstruktur.",
        },
        {
          title: "Learn the Basics of Data Science (Belajar Dasar Data Science)",
          issuer: "Dicoding Indonesia",
          issueDate: "Okt 2024",
          validity: "Okt 2024 - Okt 2027",
          description: "Eksplorasi data, analisis statistik, rekayasa fitur, pra-pemrosesan data, dan pemecahan masalah analitis.",
        },
        {
          title: "Learn the Basics of Structured Query Language (SQL)",
          issuer: "Dicoding Indonesia",
          issueDate: "Okt 2024",
          validity: "Okt 2024 - Okt 2027",
          description: "Arsitektur database relasional, kueri manipulasi data, fungsi agregasi, dan dasar manajemen basis data.",
        },
      ],
    },
    // Contact
    contact: {
      badge: "KOMUNIKASI & PERTANYAAN",
      title: "Hubungi",
      titleSpan: "Saya",
      subtitle: "Terbuka untuk posisi rekayasa teknik, kolaborasi proyek, dan diskusi riset. Silakan kirimkan pesan.",
      infoTitle: "Informasi Kontak",
      emailLabel: "Alamat Email",
      phoneLabel: "WhatsApp / Telepon Langsung",
      locationLabel: "Lokasi Saat Ini",
      locationVal: "Bekasi, Jawa Barat, Indonesia",
      affilLabel: "Latar Belakang Akademik",
      affilVal: "S1 Teknik Telekomunikasi, Telkom University",
      socialTitle: "Jaringan Profesional",
      formTitle: "Kirim Pesan Langsung",
      formSubtitle: "Isi formulir di bawah ini dan saya akan segera membalas pesan Anda.",
      nameLabel: "Nama Lengkap Anda *",
      emailInputLabel: "Alamat Email *",
      subjectLabel: "Topik / Subjek Pesan *",
      messageLabel: "Pesan *",
      namePlaceholder: "contoh: Budi Santoso",
      emailPlaceholder: "budi@perusahaan.com",
      subjectPlaceholder: "contoh: Peluang Kerja Rekayasa / Kolaborasi Proyek",
      messagePlaceholder: "Halo Raihan, saya ingin mendiskusikan tentang...",
      sendBtn: "Kirim Pesan",
      sending: "Mengirim Pesan...",
      successMsg: "✓ Terima kasih! Pesan Anda telah berhasil dikirim.",
      errorMsg: "✕ Gagal mengirim pesan. Silakan hubungi langsung via email atau WhatsApp.",
    },
    // Footer
    footer: {
      degree: "S1 Teknik Telekomunikasi - Telkom University",
      rights: "Hak Cipta Dilindungi.",
    },
  },
};

export const LanguageProvider = ({ children }) => {
  const [lang, setLang] = useState(() => {
    return localStorage.getItem("portfolio_lang") || "en";
  });

  const toggleLanguage = (selectedLang) => {
    setLang(selectedLang);
    localStorage.setItem("portfolio_lang", selectedLang);
  };

  const t = translations[lang] || translations.en;

  return (
    <LanguageContext.Provider value={{ lang, setLang: toggleLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);
